#!/bin/bash

# Replace 'foo' in any file names with 'bar'
DIR="examples"
MATCHES=0

# Parse parameters with help and directory option
while getopts "d:" opt; do
  case $opt in
    d)
      DIR=$OPTARG
      ;;
    h) 
      echo "Replace files help"
      echo "Use -d to change the default directory (examples)"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# Check files in folder
for i in `ls $DIR`
do
  # Replace 'foo' in any file names with 'bar'
  if grep -q foo $DIR/$i
  then
    mv $i ${i//foo/bar}
  else
    MATCHES=1
  fi
  # Find files to change
  if grep -l 'foo' $DIR/$i >> file_names_changed.txt
  # Replace
  then
    sed -i ' ' 's/foo/bar/g' $DIR"/"$i
  else
    CHANGED=1
  fi
done

# Print files changed 
if [[ $MATCHES==1  ]]
then
  echo "Not existing matches"
fi
if [[ $CHANGED==1 ]]
then
  echo "Not files changed"
else
  cat file_names_changed.txt
fi
